name: "terraform: initialize, and plan"
on:
  push:
    branches:
      - '!main'
      - 'dev**'
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-*.yml'
    
jobs:

  init:
    name: "terraform: setup, initialize, and plan"
    runs-on: ubuntu-latest 
    env:
      GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: checkout branch
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::406663345920:role/ucsb-role-terraform-full
          aws-region: us-west-2
          role-duration-seconds: 1200

      - name: "terraform: installing"
        uses: hashicorp/setup-terraform@v2

      - name: "terraform: init"
        run: cd terraform; terraform init -upgrade
    
      - name: "terraform: plan stage"
        id: plan
        run: cd terraform; terraform plan -no-color